nelmio_api_doc:
    documentation:
        info:
            title: BSD Smart Energy Grid API
            description: REST API for connecting to the database of the Brainport Smart Energy District
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        host_patterns:
            - ^api\.
