# Neighborhood
neighborhood_list:
  path: /api/neighborhood/all
  controller: App\Controller\NeighborhoodController:indexAction
  methods: [GET]

neighborhood_find:
  path: /api/neighborhood/{id}
  controller: App\Controller\NeighborhoodController:findByIdAction
  methods: [GET]
  requirements:
    id: '\d+'

neighborhood_delete:
  path: /api/neighborhood/{id}/delete
  controller: App\Controller\NeighborhoodController:removeByIdAction
  methods: [DELETE]
  requirements:
    id: '\d+'

neighborhood_create:
  path: /api/neighborhood/create
  controller: App\Controller\NeighborhoodController:createAction
  methods: [POST]

neighborhood_delete_all:
  path: /api/neighborhood/delete-all
  controller: App\Controller\NeighborhoodController:removeAllAction
  methods: [DELETE]

neighborhood_update:
  path: /api/neighborhood/{id}/update
  controller: App\Controller\NeighborhoodController:updateAction
  methods: [PATCH]
  requirements:
    id: '\d+'

neighborhood_get_houses:
  path: /api/neighborhood/{id}/houses
  controller: App\Controller\NeighborhoodController:getAllHouses
  methods: [GET]
  requirements:
    id: '\d+'

# House
house_list:
  path: /api/house/all
  controller: App\Controller\HouseController:indexAction
  methods: [GET]

house_find:
  path: /api/house/{id}
  controller: App\Controller\HouseController:findByIdAction
  methods: [GET]
  requirements:
    id: '\d+'

house_delete:
  path: /api/house/{id}/delete
  controller: App\Controller\HouseController:removeByIdAction
  methods: [DELETE]
  requirements:
    id: '\d+'

house_create:
  path: /api/house/create
  controller: App\Controller\HouseController:createAction
  methods: [POST]

house_delete_all:
  path: /api/house/delete-all
  controller: App\Controller\HouseController:removeAllAction
  methods: [DELETE]

house_update:
  path: /api/house/{id}/update
  controller: App\Controller\HouseController:updateAction
  methods: [PATCH]
  requirements:
    id: '\d+'

house_get_devices:
  path: /api/house/{id}/devices
  controller: App\Controller\HouseController:getAllDevices
  methods: [GET]
  requirements:
    id: '\d+'

house_get_usages:
  path: /api/house/{id}/usages
  controller: App\Controller\HouseController:getAllUsages
  methods: [GET]
  requirements:
    id: '\d+'

# Device
device_list:
  path: /api/device/all
  controller: App\Controller\DeviceController:indexAction
  methods: [GET]

device_find:
  path: /api/device/{id}
  controller: App\Controller\DeviceController:findByIdAction
  methods: [GET]
  requirements:
    id: '\d+'

device_delete:
  path: /api/device/{id}/delete
  controller: App\Controller\DeviceController:removeByIdAction
  methods: [DELETE]
  requirements:
    id: '\d+'

device_create:
  path: /api/device/create
  controller: App\Controller\DeviceController:createAction
  methods: [POST]

device_delete_all:
  path: /api/device/delete-all
  controller: App\Controller\DeviceController:removeAllAction
  methods: [DELETE]

device_update:
  path: /api/device/{id}/update
  controller: App\Controller\DeviceController:updateAction
  methods: [PATCH]
  requirements:
    id: '\d+'

device_get_usages:
  path: /api/device/{id}/usages
  controller: App\Controller\DeviceController:getAllUsages
  methods: [GET]
  requirements:
    id: '\d+'

# Usage
usage_list:
  path: /api/usage/all
  controller: App\Controller\UsageController:indexAction
  methods: [GET]

usage_find:
  path: /api/usage/{id}
  controller: App\Controller\UsageController:findByIdAction
  methods: [GET]
  requirements:
    id: '\d+'

usage_delete:
  path: /api/usage/{id}/delete
  controller: App\Controller\UsageController:removeByIdAction
  methods: [DELETE]
  requirements:
    id: '\d+'

usage_create:
  path: /api/usage/create
  controller: App\Controller\UsageController:createAction
  methods: [POST]

usage_delete_all:
  path: /api/usage/delete-all
  controller: App\Controller\UsageController:removeAllAction
  methods: [DELETE]

usage_update:
  path: /api/usage/{id}/update
  controller: App\Controller\UsageController:updateAction
  methods: [PATCH]
  requirements:
    id: '\d+'

# HouseType
house_type_list:
  path: /api/house-type/all
  controller: App\Controller\HouseTypeController:indexAction
  methods: [GET]

house_type_find:
  path: /api/house-type/{id}
  controller: App\Controller\HouseTypeController:findByIdAction
  methods: [GET]
  requirements:
    id: '\d+'

house_type_delete:
  path: /api/house-type/{id}/delete
  controller: App\Controller\HouseTypeController:removeByIdAction
  methods: [DELETE]
  requirements:
    id: '\d+'

house_type_create:
  path: /api/house-type/create
  controller: App\Controller\HouseTypeController:createAction
  methods: [POST]

house_type_delete_all:
  path: /api/house-type/delete-all
  controller: App\Controller\HouseTypeController:removeAllAction
  methods: [DELETE]

# DeviceType
device_type_list:
  path: /api/device-type/all
  controller: App\Controller\DeviceTypeController:indexAction
  methods: [GET]

device_type_find:
  path: /api/device-type/{id}
  controller: App\Controller\DeviceTypeController:findByIdAction
  methods: [GET]
  requirements:
    id: '\d+'

device_type_delete:
  path: /api/device-type/{id}/delete
  controller: App\Controller\DeviceTypeController:removeByIdAction
  methods: [DELETE]
  requirements:
    id: '\d+'

device_type_create:
  path: /api/device-type/create
  controller: App\Controller\DeviceTypeController:createAction
  methods: [POST]

device_type_delete_all:
  path: /api/device-type/delete-all
  controller: App\Controller\DeviceTypeController:removeAllAction
  methods: [DELETE]

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }
