neighborhood_list:
  path: /api/neighborhood/all
  controller: App\Controller\NeighborhoodController:indexAction
  methods: [GET]

neighborhood_find:
  path: /api/neighborhood/{id}
  controller: App\Controller\NeighborhoodController:findByIdAction
  methods: [GET]
  requirements:
    id: '\d+'

neighborhood_delete:
  path: /api/neighborhood/{id}/delete
  controller: App\Controller\NeighborhoodController:removeByIdAction
  methods: [DELETE]
  requirements:
    id: '\d+'

neighborhood_create:
  path: /api/neighborhood/create
  controller: App\Controller\NeighborhoodController:createAction
  methods: [POST]

neighborhood_delete_all:
  path: /api/neighborhood/delete-all
  controller: App\Controller\NeighborhoodController:removeAllAction
  methods: [DELETE]

neighborhood_update:
  path: /api/neighborhood/{id}/update
  controller: App\Controller\NeighborhoodController:updateAction
  methods: [PATCH]
  requirements:
    id: '\d+'

house_list:
  path: /api/house/all
  controller: App\Controller\HouseController:indexAction
  methods: [GET]

house_find:
  path: /api/house/{id}
  controller: App\Controller\HouseController:findByIdAction
  methods: [GET]
  requirements:
    id: '\d+'

house_delete:
  path: /api/house/{id}/delete
  controller: App\Controller\HouseController:removeByIdAction
  methods: [DELETE]
  requirements:
    id: '\d+'

house_create:
  path: /api/house/create
  controller: App\Controller\HouseController:createAction
  methods: [POST]

house_delete_all:
  path: /api/house/delete-all
  controller: App\Controller\HouseController:removeAllAction
  methods: [DELETE]

house_update:
  path: /api/house/{id}/update
  controller: App\Controller\HouseController:updateAction
  methods: [PATCH]
  requirements:
    id: '\d+'

